#!/usr/bin/env bash
# Serial extraction of the Pencil design (design/app.pen) to clean JSON on disk.
# CLI-ONLY (pencil interactive headless); serialized because the CLI uses a fixed socket.
# Never modifies app.pen (writes go to a throwaway --out).
set -uo pipefail

ROOT="/home/ryan/repos/Personal/ops-board"
PENCIL="/home/ryan/.local/share/pnpm/pencil"
IN="$ROOT/design/app.pen"
OUT="$ROOT/docs/design-extract"
SCRATCH="/tmp/pencil-extract-scratch.pen"
mkdir -p "$OUT/boards" "$OUT/components"

clean_json() {
  sed -e 's/\x1b\[[0-9;]*m//g' "$1" \
  | sed -e 's/^pencil[[:space:]]*>[[:space:]]*//' \
  | awk 'BEGIN{p=0} /^\{/{p=1} p==1{print} /^\}$/{if(p==1){exit}}'
}

run_pencil() { # $1 = command string, $2 = raw out file
  printf '%s\nexit()\n' "$1" | timeout 300 "$PENCIL" interactive --in "$IN" --out "$SCRATCH" > "$2" 2>&1
}

validate() { # $1 = json file -> prints "OK n_nodes bytes" or "INVALID"
  python3 - "$1" <<'PY'
import json,sys
p=sys.argv[1]
try:
    d=json.load(open(p))
    n=open(p).read().count('"id"')
    import os
    print(f"OK ids={n} bytes={os.path.getsize(p)}")
except Exception as e:
    print(f"INVALID {e}")
PY
}

MANIFEST="$OUT/EXTRACT-MANIFEST.md"
echo "# Design Extract Manifest" > "$MANIFEST"
echo "" >> "$MANIFEST"
echo "Generated by scripts/extract-design.sh from design/app.pen (CLI-only, serial)." >> "$MANIFEST"
echo "" >> "$MANIFEST"

echo "[extract] variables/tokens..."
run_pencil 'get_variables()' /tmp/raw-vars.txt
clean_json /tmp/raw-vars.txt > "$OUT/00-variables.json"
echo "- \`00-variables.json\` — $(validate "$OUT/00-variables.json")" >> "$MANIFEST"

# Board id -> slug
declare -A BOARDS=(
  [D3JA0i]="category-board-desktop"
  [a3Dgz]="timeline-desktop"
  [b1b079]="dependencies-desktop"
  [T2BChB]="voice-toasts-states"
  [h9YSWg]="mobile-screens"
  [TvXzz]="empty-loading-error-states"
  [WCTkf]="design-system"
  [GZ7xA]="ai-research-task-agent"
  [NMzE5]="account-settings-legal-manual"
  [RcvKu]="component-library"
  [vsP7L]="component-usage-map"
)
# Preserve canonical order
ORDER=(D3JA0i a3Dgz b1b079 T2BChB h9YSWg TvXzz WCTkf GZ7xA NMzE5 RcvKu vsP7L)

echo "" >> "$MANIFEST"
echo "## Boards (depth 25, full tree)" >> "$MANIFEST"
for id in "${ORDER[@]}"; do
  slug="${BOARDS[$id]}"
  echo "[extract] board $id ($slug)..."
  run_pencil "batch_get({ nodeIds: [\"$id\"], readDepth: 25 })" "/tmp/raw-board-$id.txt"
  f="$OUT/boards/${id}__${slug}.json"
  clean_json "/tmp/raw-board-$id.txt" > "$f"
  trunc=$(grep -c '"\.\.\."' "$f")
  echo "- \`boards/${id}__${slug}.json\` ($id) — $(validate "$f") truncated=$trunc" >> "$MANIFEST"
done

# 82 reusable component definitions, in 4 batches (~21 each), depth 12
COMPS=(AtbGz q7fK5p SbuAZ XDuCZ o4Fe4h PaMgT TK7Jz xpMSV tqj5T zteNg qgyiI Dn0NA HzETq iCbku f8IkAp hr3IB qrgYL Aipy6 h2sG4m fehXu zDpJJ QfQXv Dc4bO R6D1f3 kTqS3 K4DDI7 Ie7mv HLa60 db8Tm F36g7L R0QP9O dO0U6 G35WX ggMJH hHAnh lPm1x o2ncW Qi7sU MQL6i eAQ2M d2mdF X9ejlL IRZCA r9iwu Z1zBb shzZl qcfai N8Xfr2 El0g7 FLd5C rAyAF CQp4D AqpmA HgKT6 g2Ink7 ht6vH E5VLtZ Na4yA TIDIA bPiGP uJ5hm thUh3 n4lLE P5mv8T x00J9 Y1tT9d OR7jY W5Yvw Up5c1 qFALW cfa4F aRrxF C6etd5 AsyPb R8JgR ZDRoi Ht1Ql cLP7O y16GIJ YMkie d4KRE9 lLfcN)
echo "" >> "$MANIFEST"
echo "## Components (canonical reusable defs, depth 12)" >> "$MANIFEST"
echo "[extract] ${#COMPS[@]} components total" >> /dev/stderr
batch=0
i=0
while [ $i -lt ${#COMPS[@]} ]; do
  slice=("${COMPS[@]:$i:21}")
  ids=$(printf '"%s",' "${slice[@]}"); ids="[${ids%,}]"
  batch=$((batch+1))
  echo "[extract] components batch $batch (${#slice[@]} ids)..."
  run_pencil "batch_get({ nodeIds: $ids, readDepth: 12 })" "/tmp/raw-comp-$batch.txt"
  f="$OUT/components/components-batch${batch}.json"
  clean_json "/tmp/raw-comp-$batch.txt" > "$f"
  trunc=$(grep -c '"\.\.\."' "$f")
  echo "- \`components/components-batch${batch}.json\` (${#slice[@]} comps) — $(validate "$f") truncated=$trunc" >> "$MANIFEST"
  i=$((i+21))
done

echo "" >> "$MANIFEST"
echo "Done $(date -u +%FT%TZ)" >> "$MANIFEST"
echo "[extract] COMPLETE"
